#!/bin/bash

Main()
{
  BASE="${1%.*}"
  echo "Compliling $BASE.tex"
  lualatex $BASE.tex > /dev/null
  if [ $? -ne 0 ]; then
      echo "Compilation error. Check log."
      exit 1
  fi
  echo "Bibliography $BASE.tex"
  biber $BASE > /dev/null
  echo "Re-Compliling $BASE.tex"
  lualatex $BASE.tex > /dev/null
  lualatex $BASE.tex > /dev/null
  exit 0
}


MainVerbose()
{
  BASE="${1%.*}"
  lualatex $BASE.tex
  if [ $? -ne 0 ]; then
      echo "Compilation error. Check log."
      exit 1
  fi
  biber $BASE
  lualatex $BASE.tex
  lualatex $BASE.tex
  exit 0
}

Help()
{
   echo "Syntax: biblatex [-v|h] filename[.tex]"
   echo "options:"
   echo "v     Verbose mode."
   echo "h     Print this Help."
   echo
}

while getopts ":hv" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      v) # verbose mode
         MainVerbose "$2"
         exit;;
      \?) # Invalid option
        echo "Error: Invalid option"
        exit;;
   esac
done

Main "$1"
